# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_data', '0002_auto_20180111_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareserver',
            name='auto',
            field=models.BooleanField(default=True, verbose_name='是否为自动采集'),
        ),
    ]
