# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_data', '0004_auto_20180223_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareserver',
            name='auto',
            field=models.BooleanField(default=True, verbose_name='是否为自动采集'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU逻辑个数'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_physical_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU物理个数'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='total_capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='磁盘总大小(GB)'),
        ),
    ]
