# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_data', '0005_auto_20180223_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwareserver',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='softwareserver',
            name='auto',
        ),
        migrations.AddField(
            model_name='asset',
            name='auto',
            field=models.BooleanField(default=True, verbose_name='是否为自动采集'),
        ),
    ]
