# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-27 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_data', '0007_auto_20180327_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('hardwareserver', '硬件服务器'), ('softwareserver', '软件服务器'), ('networkdevice', '网络设备')], default='softwareserver', max_length=64, verbose_name='资产类型'),
        ),
    ]
