# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-28 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_data', '0012_auto_20180327_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='basic_info',
            field=models.TextField(blank=True, null=True, verbose_name='基本信息'),
        ),
    ]
