# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_data', '0013_auto_20180328_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='run_time',
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(choices=[('switch', '交换机'), ('router', '路由器'), ('firewall', '防火墙')], default='switch', max_length=64, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='manufacturer',
            field=models.CharField(choices=[('h3c', '华三'), ('juniper', '瞻博')], default='h3c', max_length=64, verbose_name='制造商'),
        ),
    ]
