# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-02 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_data', '0015_auto_20180330_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=64, unique=True, verbose_name='SN号')),
                ('manager_ip', models.GenericIPAddressField(unique=True, verbose_name='管理IP')),
                ('device_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('waf', 'WAF'), ('ads', 'ADS'), ('ips', 'IPS')], default='waf', max_length=64, verbose_name='设备类型')),
                ('manufacturer', models.CharField(choices=[('nsfocus', '绿盟')], default='h3c', max_length=64, verbose_name='制造商')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型号')),
                ('port_number', models.IntegerField(blank=True, null=True, verbose_name='接口数')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('latest_date', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchasing_company',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='采购公司'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='hardwareserver',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='idc',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='softwareserver',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='tag',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='securitydevice',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmdb_data.Asset', verbose_name='所属资产'),
        ),
    ]
