# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-02 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb_data', '0019_auto_20180402_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name_plural': 'CPU组件表'},
        ),
        migrations.AlterModelOptions(
            name='securitydevice',
            options={'verbose_name_plural': '安全设备表'},
        ),
        migrations.AlterModelOptions(
            name='softwareserver',
            options={'verbose_name_plural': '软件服务器表'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='memo',
        ),
        migrations.AlterField(
            model_name='disk',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='hardwareserver',
            name='manufacturer',
            field=models.CharField(choices=[('dell', '戴尔')], default='dell', max_length=64, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='manufacturer',
            field=models.CharField(choices=[('h3c', '华三'), ('juniper', '瞻博')], default='h3c', max_length=64, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='securitydevice',
            name='manufacturer',
            field=models.CharField(choices=[('nsfocus', '绿盟')], default='h3c', max_length=64, verbose_name='厂商'),
        ),
    ]
